useCase1/force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

useCase1/force-app/main/default/objects/Movie__c/fields/IsReleased__c.field-meta.xml
<CustomField>
    <fullName>IsReleased__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsReleased</label>
    <type>Checkbox</type>
</CustomField>

useCase1/force-app/main/default/objects/Movie__c/fields/Release_date__c.field-meta.xml
<CustomField>
    <fullName>Release_date__c</fullName>
    <label>Release date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

useCase1/force-app/main/default/classes/MovieBatch.cls
global class MovieBatch implements Database.Batchable<sObject>, Schedulable {
  global Database.QueryLocator start(Database.BatchableContext bc) {
    return Database.getQueryLocator(
      [
        SELECT Id, Release_date__c, IsReleased__c
        FROM Movie__c
      ]
    );
  }
  global void execute(Database.BatchableContext bc, List<Movie__c> movies) {
    Date today = System.today();
    for (Movie__c movie : movies) {
      if (movie.Release_date__c >= today) {
        movie.IsReleased__c = true;
      }
    }
    update movies;
  }
  global void finish(Database.BatchableContext bc) {
    System.debug('Batch done!');
  }
  global void execute(SchedulableContext sc) {
    MovieBatch movieBatch = new MovieBatch();
    Database.executeBatch(movieBatch);
  }
}