useCase1/force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

useCase1/force-app/main/default/objects/Movie__c/fields/IsReleased__c.field-meta.xml
<CustomField>
    <fullName>IsReleased__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsReleased</label>
    <type>Checkbox</type>
</CustomField>

useCase1/force-app/main/default/objects/Movie__c/fields/Release_date__c.field-meta.xml
<CustomField>
    <fullName>Release_date__c</fullName>
    <label>Release date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

useCase1/force-app/main/default/classes/BatchMovieTest.cls
@isTest
public class BatchMovieTest {
  @IsTest
  private static void testMovieBatch() {
    TestDataFactory.createSObjectList(
      'Movie__c',
      new Map<String, Object>{
        'IsReleased__c' => false,
        'Release_date__c' => System.today()
      },
      200,
      true
    );

    Test.startTest();
    MovieBatch movieBatch = new MovieBatch();
    Database.executeBatch(movieBatch);
    Test.stopTest();
    List<Movie__c> movies = [SELECT IsReleased__c FROM Movie__c];
    System.assertEquals(
      true,
      movies[0].IsReleased__c,
      'isReleased value is not correct'
    );
  }
}